name: Docker Image CI
on:
  push:
    tags:
    - "v*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: Get Release Tag
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV && ehco ${{ env.RELEASE_VERSION }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2.1.0
      with:     
       username: ${{ secrets.DOCKERHUB_USERNAME }}
       password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm
          tags: trustyboy/xxqg-helper-dev:${{ env.RELEASE_VERSION }} 
